# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: go-qlc
env:
  - GO111MODULE=on
  # - GOPROXY=https://goproxy.cn
before:
  hooks:
    # - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
    # you may remove this if you don't use vgo
    # - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./..
builds:
# Mainnet
- id: example-darwin-amd64
  binary: example
  env:
    - CGO_ENABLED=1  
    - CC=o64-clang 
    - CXX=o64-clang++
  main: ./main.go 
  goos:
    - darwin
  goarch:
    - amd64
- id: example-darwin-arm64
  binary: example
  env:
    - CGO_ENABLED=1  
    - CC=aarch64-apple-darwin20.2-clang
    - CXX=aarch64-apple-darwin20.2-clang++
  main: ./main.go 
  goos:
    - darwin
  goarch:
    - arm64
- id: example-linux
  binary: example
  env:
    - CGO_ENABLED=1
  main: ./main.go
  goos:
    - linux
  goarch:
    - amd64
- id: example-windows-x64
  ldflags: -buildmode=exe
  binary: example
  env:
    - CGO_ENABLED=1
    - CC=x86_64-w64-mingw32-gcc
    - CXX=x86_64-w64-mingw32-g++
  main: ./main.go
  goos:
    - windows
  goarch:
    - amd64

archives:
- format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: "{{ .Binary }}-v{{ .Version }}-{{ .ShortCommit }}-{{ .Os }}-{{ .Arch }}"
  replacements:
    amd64: x64
    arm64: ARM64
    darwin: macOS
    linux: Linux
    windows: Windows
  # files:
  # - README.md
  # - LICENSE
  allow_different_binary_count: true

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: SNAPSHOT-{{.ShortCommit}}


# release:
#   github:
#     owner: gythialy
#     name: golang-cross
#   prerelease: auto
