FROM debian:bullseye-slim

ENV OSX_CROSS_PATH=/osxcross

COPY "${OSX_CROSS_PATH}/*.tar.xz" "${OSX_CROSS_PATH}/tarballs/"

RUN \
  sha256sum "${OSX_CROSS_PATH}/tarballs/*.tar.xz" > "${OSX_CROSS_PATH}/tarballs/sha256sum.txt" && \
  cat "${OSX_CROSS_PATH}/tarballs/sha256sum.txt"
