name: Update depdencies

on:
  workflow_dispatch:

permissions: {}

jobs:
  check-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Check for update
        shell: bash
        run: |
          bash scripts/check-update.sh
          git config --global user.email "gythialy.koo+github@gmail.com"
          git config --global user.name "Commiter Bot"
          git commit -a -m "🤖 Updated depdencies $(date +"%Y-%m-%d")" || exit 0

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          branch-suffix: random
          assignees: gythialy
          title: Automated update dependencies by action

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
